# Generated by Django 6.0.2 on 2026-02-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='modo',
            field=models.CharField(choices=[('FOTO', 'Subir Evidencia (Manual)'), ('TIMER', 'Visita Web (Automática)')], default='FOTO', max_length=10),
        ),
        migrations.AddField(
            model_name='tarea',
            name='segundos_espera',
            field=models.IntegerField(default=0, help_text='Segundos que debe esperar el usuario para cobrar (Solo si es TIMER)'),
        ),
    ]
