# Generated by Django 6.0.2 on 2026-02-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tarea_modo_tarea_segundos_espera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retiro',
            name='email_paypal',
        ),
        migrations.AddField(
            model_name='retiro',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
