# Generated by Django 6.0.2 on 2026-02-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_retiro_email_paypal_retiro_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='fecha_subida',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='retiro',
            name='telefono',
        ),
        migrations.AddField(
            model_name='prueba',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AddField(
            model_name='retiro',
            name='cuenta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='retiro',
            name='metodo',
            field=models.CharField(default='PayPal', max_length=50),
        ),
        migrations.AddField(
            model_name='retiro',
            name='titular',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='modo',
            field=models.CharField(default='FOTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='segundos_espera',
            field=models.IntegerField(default=0),
        ),
    ]
