# Generated by Django 6.0.2 on 2026-02-08 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_fecha_subida_prueba_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='invitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='modo',
            field=models.CharField(choices=[('FOTO', '📸 Foto (Manual)'), ('TIMER', '⏳ Temporizador (Automático)')], default='FOTO', max_length=20),
        ),
    ]
